import { chromium } from 'playwright';
const sleep = ms => new Promise(r => setTimeout(r, ms));
const b = await chromium.launch(); const errs = [];
const p = await (await b.newContext({ viewport: { width: 1440, height: 900 } })).newPage();
p.on('pageerror', e => errs.push(e.message));
await p.goto('http://127.0.0.1:4173/', { waitUntil: 'load' }); await sleep(1400);
await p.screenshot({ path: 'shots/r11/es-hero.png' });
await p.evaluate(() => document.getElementById('viz').scrollIntoView()); await sleep(3200);
await p.screenshot({ path: 'shots/r11/es-viz.png' });
await p.evaluate(() => document.getElementById('swipe').scrollIntoView()); await sleep(1000);
await p.click('#bSkip'); await sleep(260 * 5 + 1500 + 3500);
await p.evaluate(() => document.getElementById('desk').scrollIntoView({ block: 'start' })); await sleep(700);
await p.screenshot({ path: 'shots/r11/es-desk.png' });
const w = await (await b.newContext({ viewport: { width: 1440, height: 900 } })).newPage();
await w.goto('http://127.0.0.1:4173/workshop/', { waitUntil: 'load' }); await sleep(1200);
await w.screenshot({ path: 'shots/r11/es-workshop.png' });
const l = await (await b.newContext({ viewport: { width: 1440, height: 900 } })).newPage();
await l.goto('http://127.0.0.1:4173/learn-more/', { waitUntil: 'load' }); await sleep(1200);
await l.screenshot({ path: 'shots/r11/es-learn.png', fullPage: false });
console.log('errors', errs); await b.close();
